apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taylor-dep-8081f732-bf4c-4096-bfab-ff14707d4f52
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/taylor-dep-8081f732-bf4c-4096-bfab-ff14707d4f52.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: taylor-dep-8081f732-bf4c-4096-bfab-ff14707d4f52
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
